import {muscleVideos,tryFirst,youtubeSearch} from './videos.js';
import {muscles,exercises} from './muscles.js';
import {bodyMap} from './anatomy.js';
import {plans} from './plans.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
const validDate=s=>typeof s==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(s)&&!isNaN(new Date(s+'T12:00:00Z'))&&new Date(s+'T12:00:00Z').toISOString().slice(0,10)===s;
const byId=id=>exercises.find(e=>e.id===id);
let previewed=null;
const activeMuscle=()=>previewed||selected;
let selected='upper-chest',priorityOnly=false,selectedDate=today(),timer=120,running=false,end=0;
const KEY='form-muscle-explorer-v1';
let state={version:1,app:'form-explorer',sessions:{}},storageReadable=true;
function validate(raw){
 if(!raw||raw.version!==1||raw.app!=='form-explorer'||!raw.sessions||typeof raw.sessions!=='object'||Array.isArray(raw.sessions))throw Error('Use a FORM Explorer version 1 backup.');
 const clean={version:1,app:'form-explorer',sessions:{}};
 if(Object.keys(raw.sessions).length>10000)throw Error('Too many sessions in this backup.');
 for(const [date,s] of Object.entries(raw.sessions)){
  if(!validDate(date)||!s||!Array.isArray(s.items)||s.items.length>exercises.length||typeof s.notes!=='string'||s.notes.length>5000)throw Error('Invalid session data.');
  const seen=new Set();const items=s.items.map(item=>{const ex=byId(item?.id);if(!ex||seen.has(item.id)||!Array.isArray(item.sets)||item.sets.length!==ex.sets)throw Error('Invalid exercise data.');seen.add(item.id);return {id:item.id,sets:item.sets.map(row=>{if(!row||typeof row.done!=='boolean'||!(row.weight===''||(typeof row.weight==='number'&&Number.isFinite(row.weight)&&row.weight>=0&&row.weight<=1000))||!(row.reps===''||(Number.isInteger(row.reps)&&row.reps>=0&&row.reps<=500)))throw Error('Invalid set data.');return {weight:row.weight,reps:row.reps,done:row.done};})};});
  clean.sessions[date]={notes:s.notes,items};
 }
 return clean;
}
let toastTimer;function toast(s){$('#toast').textContent=s;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').textContent='',4000);}
try{const raw=localStorage.getItem(KEY);if(raw)state=validate(JSON.parse(raw));}catch{storageReadable=false;setTimeout(()=>toast('Existing records could not be read. New changes stay in memory; use backup to keep them.'),100);}
function save(){try{if(!storageReadable)throw Error();localStorage.setItem(KEY,JSON.stringify(state));return true;}catch{toast('Browser storage unavailable. Use Backup / restore to keep your records.');return false;}}
const session=(create=false)=>{if(!state.sessions[selectedDate]&&create)state.sessions[selectedDate]={items:[],notes:''};return state.sessions[selectedDate]||{items:[],notes:''};};
const isAdded=id=>session().items.some(i=>i.id===id);
function updateCount(){$('#saved-count').textContent=session().items.length;}
function renderMuscleList(){let last='';$('#muscle-list').innerHTML=muscles.filter(m=>!priorityOnly||m.priority).map(m=>{const heading=m.section!==last?`<div class="muscle-group-title">${m.section.toUpperCase()}</div>`:'';last=m.section;return `${heading}<button class="muscle-item" data-select="${m.id}" aria-pressed="${m.id===selected}"><span>${m.name}</span><span class="star">${m.priority&&priorityOnly?'✦':'↗'}</span></button>`;}).join('');$('#all-muscles').setAttribute('aria-pressed',!priorityOnly);$('#priority-muscles').setAttribute('aria-pressed',priorityOnly);document.body.classList.toggle('focus-mode',priorityOnly);}
function selectMuscle(id,scroll=false){if(!muscles.some(m=>m.id===id))return;previewed=null;selected=id;$('#exercise-search').value='';$('#equipment').value='all';renderSelection();history.replaceState(null,'','#muscle='+encodeURIComponent(selected));if(scroll&&window.innerWidth<=650){$('#results').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});}}
function renderSelection(){const m=muscles.find(m=>m.id===activeMuscle());$('#muscle-name').textContent=m.name;$('#muscle-description').textContent=m.description;$('#map-name').textContent=m.name;$('#focus-badge').textContent=m.priority&&priorityOnly?'✦ UPPER-BODY FOCUS':'EXERCISE GUIDE';$('#muscle-select').value=selected;$$('[data-muscle]').forEach(el=>{const active=el.dataset.muscle===selected;el.classList.toggle('previewed',el.dataset.muscle===previewed);el.classList.toggle('selected',active);el.setAttribute('aria-pressed',active);});if(!previewed)renderMuscleList();renderMedia();renderExercises();}
function renderExercises(){const target=activeMuscle(),term=previewed?'':$('#exercise-search').value.trim().toLowerCase(),equipment=previewed?'all':$('#equipment').value;const list=exercises.filter(e=>e.muscles.includes(target)&&(equipment==='all'||e.equipment.includes(equipment))&&e.name.toLowerCase().includes(term)).sort((a,b)=>Number(b.muscles[0]===target)-Number(a.muscles[0]===target));$('#result-count').textContent=`${list.length} movement${list.length===1?'':'s'}`;$('#exercise-cards').innerHTML=list.length?list.map((e,i)=>`<article class="exercise-card"><div class="exercise-meta"><span>${String(i+1).padStart(2,'0')} / ${e.equipment.join(' · ').toUpperCase()}</span><span>${e.muscles[0]===target?e.type.toUpperCase():'ASSISTING MUSCLE'}</span></div><h3>${e.name}</h3><p>${e.cue}</p><div class="exercise-bottom"><span class="prescription">${e.sets} × ${e.reps}<small>${e.type==='Carry'?'':'REPS'}</small></span><div class="exercise-buttons"><button class="guide-button" data-guide="${e.id}">How to do it ↗</button><button class="add-button ${isAdded(e.id)?'added':''}" data-add="${e.id}" aria-label="${isAdded(e.id)?'Added to workout:':'Add to workout:'} ${e.name}" ${isAdded(e.id)?'disabled':''}>${isAdded(e.id)?'✓':'+'}</button></div></div></article>`).join(''):'<div class="empty">No matching movements for these filters.<button id="clear-filters">Clear filters</button></div>';updateCount();}
function renderMedia(){
 const id=activeMuscle(),m=muscles.find(m=>m.id===id);
 $('#selection-status').textContent=previewed?'Preview · click this muscle to keep it selected.':'Selected · hover another muscle to preview it.';
 $('#focus-suggestions').innerHTML=`<b>${m.priority&&priorityOnly?'UPPER-BODY FOCUS · TRY FIRST':'MOVEMENTS TO CONSIDER'}</b><div>${tryFirst[id].map(eid=>`<button data-guide="${eid}">${byId(eid).name} ↗</button>`).join('')}</div>`;
 $('#muscle-videos').innerHTML=`<div class="video-heading"><span>WATCH & LEARN</span><span>YouTube ↗</span></div>${muscleVideos[id].map(v=>`<a class="video-link" href="${v.url}" target="_blank" rel="noopener noreferrer"><span class="play-mark" aria-hidden="true">▶</span><span><b>${escape(v.title)}</b><small>${escape(v.creator)}${v.views?' · '+v.views+' views (snapshot)':''}</small></span><span aria-hidden="true">↗</span></a>`).join('')}<a class="popular-videos" href="${youtubeSearch(m.name+' workout exercises',true)}" target="_blank" rel="noopener noreferrer">More ${m.name.toLowerCase()} videos · sort by popularity ↗</a><p>Selected related guides, not a global most-viewed ranking. Counts shown are snapshots checked Sep 9, 2026. Popularity is not a measure of technique quality.</p>`;
}
function endPreview(){if(previewed){previewed=null;renderSelection();}}
$('#body-views').addEventListener('pointerover',e=>{if(e.pointerType==='touch'||!matchMedia('(hover: hover)').matches)return;const g=e.target.closest('[data-muscle]');if(g&&g.dataset.muscle!==activeMuscle()){previewed=g.dataset.muscle;renderSelection();}});
$('#body-views').addEventListener('pointerleave',endPreview);
$('#body-views').addEventListener('focusin',e=>{const g=e.target.closest('[data-muscle]');if(g&&g.dataset.muscle!==activeMuscle()){previewed=g.dataset.muscle;renderSelection();}});
$('#body-views').addEventListener('focusout',e=>{if(!e.currentTarget.contains(e.relatedTarget))endPreview();});
document.addEventListener('keydown',e=>{if(e.key==='Escape')endPreview();});
$('#body-views').innerHTML=bodyMap()+bodyMap(true);$('#muscle-select').innerHTML=muscles.map(m=>`<option value="${m.id}">${m.name}</option>`).join('');
$('#body-views').addEventListener('click',e=>{const g=e.target.closest('[data-muscle]');if(g)selectMuscle(g.dataset.muscle,true);});
$('#body-views').addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('[data-muscle]')){e.preventDefault();selectMuscle(e.target.dataset.muscle,true);}});
$('#muscle-list').addEventListener('click',e=>{const b=e.target.closest('[data-select]');if(b){selectMuscle(b.dataset.select,true);const next=$(`[data-select="${selected}"]`);next?.focus({preventScroll:true});}});
$('#muscle-select').addEventListener('change',e=>selectMuscle(e.target.value,true));
$('#all-muscles').addEventListener('click',()=>{priorityOnly=false;renderSelection();});$('#priority-muscles').addEventListener('click',()=>{priorityOnly=true;renderSelection();});
$('#exercise-search').addEventListener('input',renderExercises);$('#equipment').addEventListener('change',renderExercises);
function showGuide(id){const e=byId(id);$('#detail-content').innerHTML=`<h2 class="guide-title">${e.name}</h2><p>${e.muscles.map(id=>muscles.find(m=>m.id===id).name).join(' · ')}</p><div class="guide-facts"><span>${e.equipment.join(' / ')}</span><span>${e.sets} sets × ${e.reps}</span><span>Rest ${e.rest}</span></div><ol class="guide-steps">${e.steps.map(s=>`<li>${s}</li>`).join('')}</ol><p class="guide-note">${e.cue}</p><a class="guide-youtube" href="${youtubeSearch(e.name+' exercise proper form tutorial')}" target="_blank" rel="noopener noreferrer">Find ${e.name} demonstrations on YouTube ↗</a><button class="primary" data-add="${id}" ${isAdded(id)?'disabled':''}>${isAdded(id)?'Already in your workout':'Add to my workout +'}</button>`;$('#detail-dialog').showModal();}
function addExercise(id){if(!byId(id)||isAdded(id))return;session(true).items.push({id,sets:Array.from({length:byId(id).sets},()=>({weight:'',reps:'',done:false}))});const saved=save();renderExercises();renderSession();const button=$(`#detail-content [data-add="${id}"]`);if(button){button.textContent='Already in your workout';button.disabled=true;}if(saved)toast(`Added to ${selectedDate} workout.`);}
document.addEventListener('click',e=>{const guide=e.target.closest('[data-guide]'),add=e.target.closest('[data-add]'),close=e.target.closest('[data-close]');if(guide)showGuide(guide.dataset.guide);if(add)addExercise(add.dataset.add);if(close)close.closest('dialog').close();if(e.target.id==='clear-filters'){$('#exercise-search').value='';$('#equipment').value='all';renderExercises();}});
$$('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target!==d)return;const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}));
function previous(id){const dates=Object.keys(state.sessions).filter(d=>d<selectedDate).sort().reverse();for(const date of dates){const item=state.sessions[date].items.find(i=>i.id===id);if(item&&item.sets.some(s=>s.weight!==''||s.reps!=='')){return `${date}: ${item.sets.filter(s=>s.weight!==''||s.reps!=='').map(s=>`${s.weight===''?'—':s.weight} kg × ${s.reps===''?'—':s.reps}${byId(id).type==='Carry'?' sec':''}${s.done?' ✓':''}`).join(' · ')}`;}}return 'No earlier logged performance.';}
function renderSession(){$('#log-date').value=selectedDate;$('#log-notes').value=session().notes;$('#session-list').innerHTML=session().items.length?session().items.map(item=>{const e=byId(item.id);return `<article class="session-exercise"><div class="session-exercise-head"><div><h3>${e.name}</h3><small>Suggested ${e.sets} × ${e.reps}</small></div><button data-remove="${e.id}" aria-label="Remove ${e.name} from this session">Remove</button></div><div class="set-row set-head"><span>SET</span><span>KG</span><span>${e.type==='Carry'?'SECONDS':'REPS / SIDE IF NOTED'}</span><span>✓</span></div>${item.sets.map((s,i)=>`<div class="set-row"><span>${i+1}</span><input type="number" min="0" max="1000" step="any" placeholder="—" value="${s.weight}" data-id="${e.id}" data-set="${i}" data-field="weight" aria-label="${e.name}, set ${i+1}, kilograms"><input type="number" min="0" max="500" step="1" placeholder="—" value="${s.reps}" data-id="${e.id}" data-set="${i}" data-field="reps" aria-label="${e.name}, set ${i+1}, ${e.type==='Carry'?'seconds':'repetitions'}"><input type="checkbox" ${s.done?'checked':''} data-id="${e.id}" data-set="${i}" data-field="done" aria-label="${e.name}, set ${i+1}, complete"></div>`).join('')}<small>Previous · ${escape(previous(e.id))}</small></article>`;}).join(''):'<div class="empty">Your session is open.<br>Add a movement with the + button in the explorer.</div>';const dates=Object.keys(state.sessions).sort().reverse();$('#session-list').insertAdjacentHTML('beforeend',dates.length?`<label class="history-select">Open a saved date<select id="history-date"><option value="">Choose a session…</option>${dates.map(d=>`<option value="${d}">${d} · ${state.sessions[d].items.length} movements</option>`).join('')}</select></label>`:'');updateCount();}
$('#my-workout').addEventListener('click',()=>{renderSession();$('#workout-dialog').showModal();});
function changeDate(value){if(!validDate(value)){toast('Choose a valid date.');$('#log-date').value=selectedDate;return;}selectedDate=value;renderSession();renderExercises();}
$('#log-date').addEventListener('change',e=>changeDate(e.target.value));
$('#session-list').addEventListener('change',e=>{if(e.target.id==='history-date'&&e.target.value)changeDate(e.target.value);else if(e.target.matches('input')&&!e.target.validity.valid){e.target.reportValidity();const s=session().items.find(i=>i.id===e.target.dataset.id).sets[+e.target.dataset.set];e.target.value=s[e.target.dataset.field];}});
$('#session-list').addEventListener('input',e=>{const el=e.target;if(!el.dataset.id||!el.validity.valid)return;const s=session().items.find(i=>i.id===el.dataset.id).sets[+el.dataset.set];s[el.dataset.field]=el.type==='checkbox'?el.checked:el.value===''?'':+el.value;save();});
$('#session-list').addEventListener('click',e=>{const b=e.target.closest('[data-remove]');if(!b)return;const item=session().items.find(i=>i.id===b.dataset.remove);const hasLogs=item.sets.some(s=>s.done||s.weight!==''||s.reps!=='');if(hasLogs&&!confirm('Remove this exercise and its recorded sets from this session?'))return;session(true).items=session().items.filter(i=>i.id!==b.dataset.remove);save();renderSession();renderExercises();});
$('#log-notes').addEventListener('input',()=>{session(true).notes=$('#log-notes').value;save();});
$('#weekly-content').innerHTML=plans.map((p,i)=>`<details class="week-day" ${i===0?'open':''}><summary>${p.day}<span>${p.title}</span></summary>${p.ex.length?`<ol>${p.ex.map(e=>`<li>${e[0]} <span>${e[1]} × ${e[2]}</span></li>`).join('')}</ol>`:''}<p>${p.note}</p></details>`).join('');$('#weekly').addEventListener('click',()=>$('#weekly-dialog').showModal());
function drawTimer(){const s=Math.max(0,Math.ceil(timer));$('#rest-time').textContent=`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;$('#rest-start').textContent=running?'Pause':timer===0?'Restart':'Start';}
function tick(){if(running){timer=Math.max(0,(end-Date.now())/1000);if(timer===0){running=false;toast('Rest complete. Ready when you are.');}}drawTimer();}setInterval(tick,200);document.addEventListener('visibilitychange',tick);
$('#rest-start').addEventListener('click',()=>{if(running){timer=Math.max(0,(end-Date.now())/1000);running=false;}else{if(timer<=0)timer=+$('#rest-duration').value;end=Date.now()+timer*1000;running=true;}drawTimer();});function resetTimer(){running=false;timer=+$('#rest-duration').value;drawTimer();}$('#rest-reset').addEventListener('click',resetTimer);$('#rest-duration').addEventListener('change',resetTimer);
$('#backup').addEventListener('click',()=>{$('#backup-text').value=JSON.stringify(state,null,2);$('#backup-status').textContent='';$('#backup-dialog').showModal();});
$('#copy-backup').addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('#backup-text').value);$('#backup-status').textContent='Backup text copied. Paste it into a file to keep it.';}catch{$('#backup-text').select();$('#backup-status').textContent='Text selected. Press Ctrl+C (or Command+C) to copy.';}});
$('#download-backup').addEventListener('click',()=>{const url=URL.createObjectURL(new Blob([$('#backup-text').value],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`form-explorer-${today()}.json`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);$('#backup-status').textContent='Download requested. If your browser does not offer a download, use Copy text.';});
$('#restore-backup').addEventListener('click',()=>{try{const str=$('#backup-text').value;if(str.length>10000000)throw Error('Backup is too large.');const incoming=validate(JSON.parse(str));if(!confirm(`Replace existing records with ${Object.keys(incoming.sessions).length} saved sessions from this backup?`))return;state=incoming;storageReadable=true;const saved=save();renderSession();renderExercises();$('#backup-status').textContent=saved?'Backup restored.':'Restored in memory. Browser storage is unavailable; keep your backup.';}catch(e){$('#backup-status').textContent=e instanceof SyntaxError?'Invalid JSON. Paste a complete backup.':e.message;}});
renderSelection();renderSession();

function readMuscleLink(){const id=new URLSearchParams(location.hash.slice(1)).get('muscle');if(muscles.some(m=>m.id===id)){previewed=null;selected=id;$('#exercise-search').value='';$('#equipment').value='all';renderSelection();}}
window.addEventListener('hashchange',readMuscleLink);readMuscleLink();
$('#share-muscle').addEventListener('click',()=>{if(previewed)selectMuscle(previewed);$('#share-url').value='https://workout-gudie.netlify.app/#muscle='+encodeURIComponent(selected);$('#share-status').textContent='';$('#native-share').hidden=!navigator.share;$('#share-dialog').showModal();});
$('#copy-muscle').addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('#share-url').value);$('#share-status').textContent='Link copied. Ready to send.';}catch{$('#share-url').select();$('#share-status').textContent='Select and copy the link above.';}});
$('#native-share').addEventListener('click',async()=>{try{await navigator.share({title:'Workout Gudie · '+muscles.find(m=>m.id===selected).name,url:$('#share-url').value});}catch(e){if(e.name!=='AbortError')$('#share-status').textContent='Sharing is unavailable here. Copy the link instead.';}});
$('#how-it-works').addEventListener('click',()=>$('#help-dialog').showModal());$('#privacy-info').addEventListener('click',()=>$('#privacy-dialog').showModal());
