export const muscles = [
['upper-chest','Upper chest','Upper body',true,'Emphasize the upper portion of your chest with incline presses and upward cable-fly paths. Choose a variation that fits your available equipment.'],
['chest','Chest','Upper body',false,'Build your chest with horizontal presses and controlled fly movements. Your front delts and triceps assist during pressing.'],
['lats','Lats','Upper body',true,'Train the broad muscles along the sides of your back with vertical pulls and rows. Use a controlled reach and pull.'],
['upper-back','Upper back','Upper body',true,'Rows train the muscles around your shoulder blades. Use controlled repetitions without turning each pull into a shrug.'],
['side-delts','Side delts','Upper body',true,'Lateral raises give the side delts more specific work than relying on pressing alone.'],
['rear-delts','Rear delts','Upper body',true,'Train the back of your shoulders with reverse flyes and controlled rows. These complement pressing and lateral-raise movements.'],
['front-delts','Front delts','Upper body',false,'The front of your shoulders already works during chest presses. Add direct pressing only as it fits your overall volume and recovery.'],
['biceps','Biceps','Arms & core',false,'Train elbow flexion with controlled curls. Keep your torso still and choose a comfortable grip.'],
['triceps','Triceps','Arms & core',false,'Train elbow extension with overhead extensions and pressdowns. Pressing movements also contribute triceps work.'],
['forearms','Forearms','Arms & core',false,'Develop your grip and forearms with carries and curls. Keep the wrists controlled and loads manageable.'],
['core','Core','Arms & core',false,'Build trunk strength with controlled flexion and anti-extension exercises. Core training does not selectively remove belly fat.'],
['quads','Quads','Lower body',false,'Train the front of your thighs with squats, leg presses, and single-leg work. Choose a stable setup and a range you can control.'],
['hamstrings','Hamstrings','Lower body',false,'Combine hip hinges with knee-flexion work to train the back of your thighs. Keep the movement controlled through a comfortable range.'],
['glutes','Glutes','Lower body',false,'Build hip-extension strength with thrusts, squats, and lunges. Keep lower-body work balanced throughout the week.'],
['calves','Calves','Lower body',false,'Use standing and seated calf raises with a controlled stretch and lift. Avoid bouncing through the bottom.']
].map(([id,name,section,priority,description])=>({id,name,section,priority,description}));
const patterns = {
 incline:['Set the bench at a low-to-moderate incline, around 20–30°. Plant your feet and set your upper back.','Lower the weights under control with forearms roughly vertical. Use a comfortable elbow angle.','Press upward without bouncing or lifting your hips, then repeat through a range you can control.'],
 press:['Set your feet and upper back firmly. Position the handles or weights around chest level.','Lower under control through a comfortable range, with wrists stacked above the forearms.','Press smoothly; keep the shoulders stable and avoid bouncing the weight.'],
 fly:['Set the handles and take a balanced stance. Keep a soft, consistent bend in your elbows.','Bring your arms together through the intended arc without turning the movement into a press.','Return slowly until you feel a comfortable stretch; keep your torso still.'],
 pull:['Set a secure grip and sit or hang in a stable position. Brace your trunk.','Bring your elbows toward your hips as you pull. Avoid swinging or leaning excessively.','Return under control, allowing a comfortable reach before the next repetition.'],
 row:['Set a stable torso position and a secure grip. Support your chest if the exercise uses a bench.','Draw your elbows back while keeping your neck relaxed and your shoulders away from your ears.','Return slowly, letting the shoulder blades move naturally without losing trunk control.'],
 lateral:['Stand tall with a light load at your side and a slight bend in your elbows.','Raise your arms out to the sides in a comfortable plane, up to roughly shoulder height.','Lower slowly. Keep your torso still and avoid throwing or shrugging the weight up.'],
 reverse:['Position your chest against the pad or hinge from the hips for the dumbbell version.','With softly bent elbows, open your arms outward, keeping the shoulders away from your ears.','Return under control. Use a load that lets your rear shoulders do the work without momentum.'],
 curl:['Hold the load with a stable wrist and a still torso. Set your upper arms in the intended position.','Bend your elbows to lift the weight without swinging your body or driving the elbows forward.','Lower under control, keeping a comfortable range and avoiding a sudden drop at the bottom.'],
 extension:['Set a stable stance and keep the upper arms relatively still. Grip the attachment securely.','Extend your elbows through a comfortable range without using your torso to move the load.','Bend the elbows slowly to return. Adjust the load if you cannot keep control.'],
 squat:['Set a stable stance and brace your trunk. Keep your feet in full contact with the floor or platform.','Bend the knees and hips together, letting the knees follow the direction of the toes.','Drive back up through the feet. Use a depth you can control without losing position.'],
 hinge:['Stand with a stable grip and softly bent knees. Brace your trunk before moving.','Push the hips back, keeping the load close and the back position steady. Stop before losing control.','Drive the hips forward to stand tall. Do not lean back or jerk the load at the top.'],
 lunge:['Take a stable split stance or step back as appropriate. Keep your front foot planted.','Lower under control, bending both knees and keeping the front knee tracking with the toes.','Push through the front foot to return. Complete the prescribed repetitions on each leg.'],
 legcurl:['Adjust the machine so its knee pivot aligns with your knee and its pad rests above the heel.','Curl the pad through a comfortable range while keeping your hips steady against the support.','Return slowly instead of letting the weight stack drop.'],
 calf:['Place the balls of your feet securely on the platform; keep support nearby for balance.','Lower your heels through a comfortable stretch, then rise onto the balls of your feet.','Pause briefly at the top and lower slowly. Avoid bouncing or rolling the ankles.'],
 crunch:['Choose a position where you can control the pelvis and trunk. Start with a manageable load.','Curl through the trunk slowly instead of pulling with the arms or using momentum.','Return under control and breathe between repetitions.'],
 rollout:['Start kneeling with the wheel below your shoulders. Brace your trunk and gently tuck the pelvis.','Roll forward only as far as you can without the lower back sagging.','Pull back to the start under control. Shorten the reach when you cannot maintain position.'],
 thrust:['Support the upper back on a stable bench and place the load securely across the hips.','Drive through the feet and lift the hips while keeping your ribs down.','Stop when the hips are extended, without arching the lower back; lower under control.'],
 shoulder:['Set a stable seated or standing position with the weights at shoulder level.','Press upward in a comfortable path without leaning back or flaring the rib cage.','Lower slowly to shoulder level, keeping the wrists stacked and the trunk steady.'],
 carry:['Pick up manageable weights with a stable trunk and hold them at your sides.','Walk with short, controlled steps while staying tall and keeping the shoulders relaxed.','Set the weights down under control. Stop the carry before your grip or posture breaks down.']
};
export const exercises = [
['incline-db','Incline dumbbell press',['upper-chest','front-delts','triceps'],['Dumbbells'],4,'6–10','Compound','incline','A main upper-chest movement; keep the incline modest.'],
['incline-bb','Incline barbell press',['upper-chest','front-delts','triceps'],['Barbell'],4,'6–10','Compound','incline','Use rack safeties or an appropriate spotter for barbell pressing.'],
['incline-machine','Incline machine press',['upper-chest','front-delts','triceps'],['Machine'],3,'8–12','Compound','press','Adjust the seat so the press follows an upward chest-level path.'],
['upward-fly','Low-to-high cable fly',['upper-chest','chest'],['Cable'],2,'12–15','Isolation','fly','Start with low pulleys and bring the handles upward and inward.'],
['flat-db','Flat dumbbell press',['chest','front-delts','triceps'],['Dumbbells'],3,'8–12','Compound','press','A horizontal press for general chest development.'],
['chest-machine','Machine chest press',['chest','front-delts','triceps'],['Machine'],3,'8–12','Compound','press','A supported option when you want a stable pressing setup.'],
['pushup','Push-up',['chest','front-delts','triceps'],['Bodyweight'],3,'8–15','Compound','press','Keep a straight line from head to heels. Elevate your hands if needed.'],
['pulldown','Neutral-grip pulldown',['lats','biceps'],['Cable','Machine'],3,'8–12','Compound','pull','Think elbows toward hips. Keep your torso quiet.'],
['pullup','Pull-up',['lats','upper-back','biceps'],['Bodyweight'],3,'6–10','Compound','pull','Use a secure pull-up bar. Choose assistance if needed to control the full repetition.'],
['single-pull','Single-arm cable pulldown',['lats'],['Cable'],3,'10–15 / side','Compound','pull','Train one side at a time without twisting to finish the pull.'],
['chest-row','Chest-supported dumbbell row',['upper-back','lats','rear-delts'],['Dumbbells'],3,'8–12','Compound','row','Let the bench support your torso so you can focus on the pull.'],
['cable-row','Seated cable row',['upper-back','lats','biceps'],['Cable'],3,'8–12','Compound','row','Pull toward your torso without rocking back and forth.'],
['lateral-cable','Cable lateral raise',['side-delts'],['Cable'],4,'12–20','Isolation','lateral','A focused choice for your side delts. Lead with the elbow, not a shrug.'],
['lateral-db','Dumbbell lateral raise',['side-delts'],['Dumbbells'],3,'12–20','Isolation','lateral','A straightforward alternative when a cable station is busy.'],
['reverse-deck','Reverse pec deck',['rear-delts','upper-back'],['Machine'],3,'12–20','Isolation','reverse','Adjust the seat so your arms open at a comfortable shoulder height.'],
['rear-cable','Rear-delt cable fly',['rear-delts'],['Cable'],3,'12–20','Isolation','reverse','Use a light load and open the arms without excessive shrugging.'],
['rear-db','Bent-over dumbbell reverse fly',['rear-delts'],['Dumbbells'],3,'12–20','Isolation','reverse','Hinge at the hips and keep the torso still as your arms open.'],
['shoulder-press','Dumbbell shoulder press',['front-delts','side-delts','triceps'],['Dumbbells'],3,'8–12','Compound','shoulder','Optional direct shoulder pressing; account for the pressing already in your week.'],
['incline-curl','Incline dumbbell curl',['biceps'],['Dumbbells'],3,'8–12','Isolation','curl','Sit against an inclined bench and keep your upper arms from drifting forward.'],
['hammer','Hammer curl',['biceps','forearms'],['Dumbbells'],2,'10–15','Isolation','curl','Keep a neutral, palms-facing-in grip throughout the repetition.'],
['ez-curl','EZ-bar curl',['biceps','forearms'],['Barbell'],3,'8–12','Isolation','curl','Use a comfortable grip on the angled bar and avoid torso swing.'],
['overhead-ext','Overhead cable triceps extension',['triceps'],['Cable'],3,'10–15','Isolation','extension','Start with the upper arms overhead in a comfortable position.'],
['pressdown','Rope pressdown',['triceps'],['Cable'],3,'10–15','Isolation','extension','Keep the elbows near your sides as you straighten your arms.'],
['carry','Farmer carry',['forearms'],['Dumbbells'],3,'20–40 sec','Carry','carry','A grip-focused alternative. The prescription is time, not repetitions.'],
['squat','Barbell squat',['quads','glutes'],['Barbell'],3,'6–10','Compound','squat','Set rack safeties for your depth and use warm-up sets before loading.'],
['hack','Hack squat',['quads','glutes'],['Machine'],3,'6–10','Compound','squat','Set the machine stops and keep your back supported through the movement.'],
['leg-press','Leg press',['quads','glutes'],['Machine'],3,'8–12','Compound','squat','Use a range that keeps your pelvis against the pad.'],
['split','Bulgarian split squat',['quads','glutes'],['Dumbbells','Bodyweight'],2,'8–12 / leg','Compound','lunge','Rest the rear foot on a stable low support; find your balance before adding load.'],
['reverse-lunge','Reverse lunge',['quads','glutes'],['Dumbbells','Bodyweight'],2,'8–12 / leg','Compound','lunge','Step backward to create the split stance, then return through the front foot.'],
['rdl','Romanian deadlift',['hamstrings','glutes'],['Barbell','Dumbbells'],3,'6–10','Compound','hinge','This is a hip hinge. Keep the knees softly bent rather than squatting the weight.'],
['seated-curl','Seated leg curl',['hamstrings'],['Machine'],3,'10–15','Isolation','legcurl','Secure the thigh pad and keep your hips down while curling.'],
['lying-curl','Lying leg curl',['hamstrings'],['Machine'],3,'10–15','Isolation','legcurl','Keep your hips on the pad rather than lifting them to finish.'],
['hip-thrust','Hip thrust',['glutes'],['Barbell','Machine'],3,'8–12','Compound','thrust','Use padding with a barbell and a stable setup. Finish with the hips, not the low back.'],
['standing-calf','Standing calf raise',['calves'],['Machine','Dumbbells','Bodyweight'],3,'8–15','Isolation','calf','Keep the knees mostly straight but not forced into a hard lock.'],
['seated-calf','Seated calf raise',['calves'],['Machine'],3,'10–20','Isolation','calf','The bent-knee position complements standing calf work.'],
['cable-crunch','Cable crunch',['core'],['Cable'],3,'10–15','Isolation','crunch','Hold the rope near your head and curl the trunk; avoid just hinging at the hips.'],
['knee-raise','Hanging knee raise',['core'],['Bodyweight'],3,'8–15','Isolation','crunch','Use a secure bar, raise the knees and gently curl the pelvis without swinging.'],
['ab-wheel','Ab-wheel rollout',['core'],['Bodyweight'],3,'6–12','Isolation','rollout','Requires an ab wheel. Start with a short kneeling rollout you can control.']
].map(([id,name,muscles,equipment,sets,reps,type,pattern,cue])=>({id,name,muscles,equipment,sets,reps,type,cue,steps:patterns[pattern],rest:type==='Compound'?'2–3 min':'60–90 sec'}));
exercises.find(e=>e.id==='pushup').steps=['Set your hands slightly wider than shoulder width, and hold a straight line from head to heels. Use an elevated hand position if needed.','Bend your elbows to lower the chest toward the floor, keeping the trunk braced and the elbows at a comfortable angle.','Push the floor away to return without letting the hips sag or the shoulders shrug.'];
exercises.find(e=>e.id==='knee-raise').steps=['Hold a secure bar with a controlled, supported shoulder position. Let the legs hang without swinging.','Raise the knees, then gently curl the pelvis toward the ribs. Keep the movement slow.','Lower your legs under control. End the set when you can no longer prevent swinging.'];
